{
    "config": {
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Hoszt",
                    "password": "Jelsz\u00f3",
                    "username": "Felhaszn\u00e1l\u00f3n\u00e9v"
                },
                "data_description": {
                    "host": "A Lutron f\u0151 \u00e1tj\u00e1tsz\u00f3 g\u00e9pneve vagy IP-c\u00edme."
                },
                "description": "K\u00e9rj\u00fck, adja meg a f\u0151 \u00e1tj\u00e1tsz\u00f3 bejelentkez\u00e9si adatait",
                "title": "F\u0151 \u00e1tj\u00e1tsz\u00f3 be\u00e1ll\u00edt\u00e1sa"
            }
        }
    },
    "entity": {
        "event": {
            "button": {
                "state_attributes": {
                    "event_type": {
                        "state": {
                            "press": "Gombnyom\u00e1s",
                            "release": "Felenged\u00e9s",
                            "single_press": "Egyszeri gombnyom\u00e1s"
                        }
                    }
                }
            }
        }
    },
    "options": {
        "step": {
            "init": {
                "data": {
                    "default_dimmer_level": "Alap\u00e9rtelmezett f\u00e9nyer\u0151szint, amikor egy l\u00e1mp\u00e1t el\u0151sz\u00f6r bekapcsol a Home Assistantb\u00f3l"
                }
            }
        }
    }
}