{
    "config": {
        "abort": {
            "already_configured": "Zariadenie u\u017e je nakonfigurovan\u00e9",
            "home_control": "Centr\u00e1lna jednotka devolo Home Control nefunguje s touto integr\u00e1ciou.",
            "reauth_successful": "Op\u00e4tovn\u00e9 overenie bolo \u00faspe\u0161n\u00e9"
        },
        "error": {
            "cannot_connect": "Nepodarilo sa pripoji\u0165",
            "invalid_auth": "Neplatn\u00e9 overenie",
            "unknown": "Neo\u010dak\u00e1van\u00e1 chyba"
        },
        "flow_title": "{product} ({name})",
        "step": {
            "reauth_confirm": {
                "data": {
                    "password": "Heslo"
                },
                "data_description": {
                    "password": "Heslo, ktor\u00fdm ste zariadenie chr\u00e1nili."
                }
            },
            "user": {
                "data": {
                    "ip_address": "IP adresa",
                    "password": "Heslo"
                },
                "data_description": {
                    "ip_address": "IP adresa zariadenia devolo Home Network. T\u00fa n\u00e1jdete v aplik\u00e1cii devolo Home Network na ovl\u00e1dacom paneli zariadenia.",
                    "password": "Heslo, ktor\u00fdm ste zariadenie chr\u00e1nili."
                },
                "description": "Chcete za\u010da\u0165 nastavova\u0165?"
            },
            "zeroconf_confirm": {
                "data": {
                    "password": "Heslo"
                },
                "data_description": {
                    "password": "Heslo, ktor\u00fdm ste zariadenie chr\u00e1nili."
                },
                "description": "Chcete prida\u0165 zariadenie devolo Home Network s n\u00e1zvom hostite\u013ea `{host_name}` do aplik\u00e1cie Home Assistant?",
                "title": "Objaven\u00e9 zariadenie devolo Home Network"
            }
        }
    },
    "entity": {
        "binary_sensor": {
            "connected_to_router": {
                "name": "Pripojen\u00e9 k routru"
            }
        },
        "button": {
            "identify": {
                "name": "Identifikujte zariadenie pomocou blikaj\u00facej LED"
            },
            "pairing": {
                "name": "Spustenie p\u00e1rovania PLC"
            },
            "restart": {
                "name": "Re\u0161tartovanie zariadenia"
            },
            "start_wps": {
                "name": "Spustenie WPS"
            }
        },
        "image": {
            "image_guest_wifi": {
                "name": "Prihlasovacie \u00fadaje hos\u0165a Wifi ako k\u00f3d QR"
            }
        },
        "sensor": {
            "connected_plc_devices": {
                "name": "Pripojen\u00e9 zariadenia PLC"
            },
            "connected_wifi_clients": {
                "name": "Pripojen\u00ed Wifi klienti"
            },
            "last_restart": {
                "name": "Posledn\u00fd re\u0161tart zariadenia"
            },
            "neighboring_wifi_networks": {
                "name": "Susedn\u00e9 Wifi siete"
            },
            "plc_rx_rate": {
                "name": "PLC downlink r\u00fdchlos\u0165 PHY"
            },
            "plc_tx_rate": {
                "name": "PLC uplink r\u00fdchlos\u0165 PHY"
            }
        },
        "switch": {
            "switch_guest_wifi": {
                "name": "Povoli\u0165 WiFi pre host\u00ed"
            },
            "switch_leds": {
                "name": "Povoli\u0165 LED di\u00f3dy"
            }
        }
    },
    "exceptions": {
        "connection_failed": {
            "message": "Ned\u00e1 sa pripoji\u0165 k {ip_address}"
        },
        "no_response": {
            "message": "Zariadenie {title} nereagovalo"
        },
        "password_protected": {
            "message": "Zariadenie {title} vy\u017eaduje op\u00e4tovn\u00e9 overenie na nastavenie alebo zmenu hesla"
        },
        "password_wrong": {
            "message": "Pou\u017eit\u00e9 heslo je nespr\u00e1vne"
        },
        "update_failed": {
            "message": "Chyba pri aktualiz\u00e1cii \u00fadajov: {error}"
        }
    }
}